import Navbar from '@/UI/components/Navbar'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="md:block hidden">
        <Navbar />
      </div>
      {children}
    </div>
  )
}
