import Navbar from '@/UI/components/Navbar'
import type { Metadata } from 'next'
import backImg from '../../public/assets/images/button.svg'
import Link from 'next/link'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <div className="md:block hidden">
        <Navbar />
      </div>
      <div className="font-clash text-lg text-[#D434FE] flex items-center space-x-2 md:hidden border-none pt-7 pb-10 px-16 bg-[#150E28]">
        <Link href={'/'}>
          <Image placeholder="blur"  src={backImg} alt="" />
        </Link>
        <p>Register</p>
      </div>
      {children}
    </div>
  )
}
